### ISSUE TITLE
Uploading multiple files at once

### ISSUE THREAD

**Issue by stumi01** [lokalise/lokalise-cli-2-go#1]
We are trying to migrate from the cli v1 and seems the `file` attribute does not want to handle multiple files.

v1 command was:
```   
 ./lokalise --token ${LOKALISE_TOKEN} import ${LOCALISE_PROJECT} --lang_iso en --file app/src/main/res/values/strings.xml,app/src/main/res-features/profile/values/strings.xml --include_path 1
```
v2 command:
```
    ./lokalise2 file upload --token ${LOKALISE_TOKEN} --project-id ${LOCALISE_PROJECT} --lang-iso en --file app/src/main/res/values/strings.xml,app/src/main/res-features/profile/values/strings.xml
```

the command works fine with only 1 file but does nothing (not even an error message) when used like this

**Comment by nickustinov** [comment]
Thanks for reporting, let us investigate.;

**Comment by nickustinov** [comment]
@stumi01 Please update to version 2.02, the issue should be resolved. Also we have added --include-path flag to preserve the full path in the filename.

**Comment by kirrg001** [comment]
Is a folder parameter planned? e.g. `--folder ./pubic/locales`
Uploads de/**.json and en/**json and also auto-detects the language based on locale folder name.

It's a little complicated defining **all** locale files per language manually.
