### ISSUE TITLE
Installer script returns exit code 1

### ISSUE THREAD

**Issue by EmDee** [lokalise/lokalise-cli-2-go#10]
### Problem

Running the installer script returns exit code 1.

```shell
curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
```

The script worked earlier today so I assume the latest PR merge somehow change/broke the behavior.

**Comment by yarlson** [comment]
Thank you for spotting that! Fixed!

**Comment by EmDee** [comment]
Thanks for the quick fix. I don't get an exit code 1 anymore, however, when I run `lokalise2` I suddenly get an `API request error 404 Not Found` error. New issue?

FYI: Everything works fine with the old binary, i.e. https://github.com/lokalise/lokalise-cli-2-go/releases/download/v2.1.0/lokalise-cli-2-go_2.1.0_Linux_x86_64.tar.gz

**Comment by b95505017** [comment]
Same 404 issue here

**Comment by EmDee** [comment]
I've created a new ticket for that issue so is easier to find: https://github.com/lokalise/lokalise-cli-2-go/issues/11
