### ISSUE TITLE
API request error 406 No keys for export with current export settings

### ISSUE THREAD

**Issue by bviebahn** [lokalise/lokalise-cli-2-go#103]
I'm trying to download the locale files using
```
lokalise2 --project-id <id> --token <token> file download --format json --unzip-to ./locales
```

And I'm getting
```
API request error 406 No keys for export with current export settings
```
Any idea how to fix this?

**Comment by bviebahn** [comment]
Fixed it by using the `--all-platforms` option.

**Comment by SoohyungJung** [comment]
> Fixed it by using the `--all-platforms` option.

@bviebahn 
You saved my life. Thank you for sharing your solution!
