### ISSUE TITLE
No docker container for ARM architecture

### ISSUE THREAD

**Issue by rchl** [lokalise/lokalise-cli-2-go#117]
There is currently no docker container built for ARM architecture (for M-series macs or Linux) in https://hub.docker.com/r/lokalise/lokalise-cli-2

It would be a bit more efficient to run a container dedicated for the given architecture.

**Comment by yarlson** [comment]
Starting with `lokalise/lokalise-cli-2:v2.6.9`, both AMD64 and ARM64 platforms are supported.
