### ISSUE TITLE
CLI no longer works, still using outdated api.lokalise.co

### ISSUE THREAD

**Issue by frenck** [lokalise/lokalise-cli-2-go#119]
Seems like this CLI no longer works, we get this error message on the Home Assistant project:

![CleanShot 2023-10-02 at 22 04 29](https://github.com/lokalise/lokalise-cli-2-go/assets/195327/d77d37f1-e8d5-4734-ba3c-44aa05172901)

Seems like `api.lokalise.co` is no longer available and was renamed to `api.lokalise.com`. However, this CLI doesn't use that.

Is this CLI still maintained? The last commit was in Oct 2021, yet it is listed in the official docs.

Please note, that the Go library used by this CLI was already updated in 2020; however, never propagated into this client, see: <https://github.com/lokalise/go-lokalise-api/commit/dfca20dabe7b1e6b8e781ecffdde6f8adc1ceddb>

This is currently blocking our software release process. Please advise.

**Comment by frenck** [comment]
Nevermind, this was a fault on our end. Sorry for the noise 🙏 

Yet, this client seems to be unmaintained?

**Comment by unr** [comment]
@frenck what was the issue? 👀
