### ISSUE TITLE
The version 2.6.9 break my Github action 

### ISSUE THREAD

**Issue by flemaitre33** [lokalise/lokalise-cli-2-go#121]
Hello,

since the last version `v.2.6.9` my github action to get translation files is broken.

On version `v.2.6.8` is ok 

<img width="1077" alt="image" src="https://github.com/lokalise/lokalise-cli-2-go/assets/127124896/78c3821c-9bf2-445f-bb55-746745fb960a">

On version `v.2.6.9` install return error code

<img width="1042" alt="image" src="https://github.com/lokalise/lokalise-cli-2-go/assets/127124896/d23fee8f-3190-4587-b9aa-39b709728803">

Can you check this issue please ?

Florent

**Comment by rodrigofeijao** [comment]
I'm having the same issue. 
For those stuck you can try to install the previous version: 
```
curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/v2.6.8/install.sh | sh -s -- v2.6.8
```

**Comment by stuartleigh** [comment]
for anyone trying to debug, when running with -d we get


#35 [translator 4/8] RUN curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/v2.6.8/install.sh \| sh -s -- -d
--
  | #35 sha256:582fd440441316a96a99d82f8b64d27c6390e80ee1a826d1783fc25842ba26c9
  | #35 0.776 lokalise/lokalise-cli-2-go info checking GitHub for latest tag
  | #35 0.777 lokalise/lokalise-cli-2-go debug http_download https://github.com/lokalise/lokalise-cli-2-go/releases/latest
  | #35 1.080 lokalise/lokalise-cli-2-go info found version: 2.6.9 for v2.6.9/linux/x86_64
  | #35 1.081 lokalise/lokalise-cli-2-go debug downloading files into /tmp/tmp.NGEjnM
  | #35 1.082 lokalise/lokalise-cli-2-go debug http_download https://github.com/lokalise/lokalise-cli-2-go/releases/download/v2.6.9/lokalise2_linux_x86_64.tar.gz
  | #35 1.324 lokalise/lokalise-cli-2-go debug http_download_curl received HTTP status 404

**Comment by flemaitre33** [comment]
On macos m1 (darwin_arm64) is Ok

```
➜  ~ curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh |  sh -s -- -d
lokalise/lokalise-cli-2-go info checking GitHub for latest tag
lokalise/lokalise-cli-2-go debug http_download https://github.com/lokalise/lokalise-cli-2-go/releases/latest
lokalise/lokalise-cli-2-go info found version: 2.6.9 for v2.6.9/darwin/arm64
lokalise/lokalise-cli-2-go debug downloading files into /var/folders/t4/8y65g0ws3f73qr9995k71_sm0000gq/T/tmp.68Yhjlhv
lokalise/lokalise-cli-2-go debug http_download https://github.com/lokalise/lokalise-cli-2-go/releases/download/v2.6.9/lokalise2_darwin_arm64.tar.gz
lokalise/lokalise-cli-2-go debug http_download https://github.com/lokalise/lokalise-cli-2-go/releases/download/v2.6.9/checksums.txt
lokalise/lokalise-cli-2-go info installed ./bin/lokalise2
```

**Comment by mlankamp** [comment]
I think the problem is caused by this change:
https://github.com/lokalise/lokalise-cli-2-go/commit/2ba2568569c6a1f31f68e44a8135c622f42bc7d7

**Comment by ans-ioki** [comment]
I guess it is a change in the way releases work. It broke for me as well, maybe @yarlson is deeper into this and knows exactly whats going on... i guess https://github.com/lokalise/lokalise-cli-2-go/commit/1b7e4c70fdd043eb6ec0caf821d873623dd4a40c changes the namings. As the project readme says one can fetch releases with builds from static urls like these: `https://github.com/lokalise/lokalise-cli-2-go/releases/latest/download/lokalise2_linux_x86_64.tar.gz` the "latest" part is broken and so wgetting stuff in our actions are broken.

If i see this correctly one can temporarily "pin" / fix your own GHA by not using the urls with the `/releases/latest/download/` fragment in there, but must replace it to some static value, like `/releases/download/v2.6.9`. (note the different order). At least i am able to get the 2.6.8 with `wget --no-verbose https://github.com/lokalise/lokalise-cli-2-go/releases/download/v2.6.9/lokalise2_linux_x86_64.tar.gz` atm.

**Comment by yarlson** [comment]
Goreleaser update has changed the names of the binaries, will address the issue ASAP

**Comment by yarlson** [comment]
2.6.10 has been released, the paths have been fixed.

**Comment by mlankamp** [comment]
Works on my end (maybe delete the v2.6.9 release?)

**Comment by flemaitre33** [comment]
Version 2.6.10 works fine 👍 

<img width="817" alt="image" src="https://github.com/lokalise/lokalise-cli-2-go/assets/127124896/b145ec0f-0243-421d-bbd5-8fa2dc2208a0">

Thanks @yarlson && @mlankamp

**Comment by ans-ioki** [comment]
Thank you, @yarlson !
