### ISSUE TITLE
Getting multiple files with `--original-filenames false`

### ISSUE THREAD

**Issue by mkaplan9** [lokalise/lokalise-cli-2-go#14]
Using `lokalise2 file download --format json --original-filenames false` , I'm receiving two files for several locales (`no_filename.json` and `ar.json` for Arabic for instance). From the docs:
```
--original-filenames Enable to use original filenames/formats. If set to false all keys will be export to a single file per language (default true)
```

**Comment by yarlson** [comment]
@mkaplan9 Boolean parameters should be passed via = sign, so it should be `--original-filenames=false`. Have you tried it?

**Comment by mkaplan9** [comment]
That fixed it, thank you!
