### ISSUE TITLE
Export result always have parent `locale` folder

### ISSUE THREAD

**Issue by pinarmrv** [lokalise/lokalise-cli-2-go#168]
lokalise2 CLI version: `3.0.1`

I have the following configuration to download files. Is there any option to remove parent folder `locale`? I went through the file download documentation. I think it would be great to have a flag, so we can customize folder structure as we want.

```
lokalise2 \
--token <TOKEN> \
--project-id <P-ID> \
file download \
--format properties \
--all-platforms \
--original-filenames=false \
--java-properties-separator "=" \
--java-properties-encoding="utf-8" \
--include-description=false \
--include-comments=false \
--unzip-to "./i18n"
```

**Comment by N7K4** [comment]
I can confirm that it happen as well on format `resx`, not only on `properties `. I would guess it happen on all **file download** operations.

**Comment by pinarmrv** [comment]
After spending time with the editor, I noticed that `--bundle-structure` flag was needed. Closing this issue, but I still think that the documentation can be improved, since it was not obvious without interaction with the UI.
