### ISSUE TITLE
Error from `task create`

### ISSUE THREAD

**Issue by mkaplan9** [lokalise/lokalise-cli-2-go#21]
I'm getting the following error when I call `lokalise2 task create`:
```
Error: json: cannot unmarshal array into Go struct field TaskLanguage.task.languages.initial_tm_leverage of type map[string]int64
```

The task actually still gets created and it looks OK in the UI. I'm using:
```
--initial-tm-leverage=false
--languages [{"language_iso": my_lang_iso, "groups": [my_int]}]
```

Am I formatting something incorrectly?

**Comment by beinarovic** [comment]
Hey @mkaplan9 ,

Sorry for the late response, this got fixed lately.
