### ISSUE TITLE
Task list/retrieve commands are failing

### ISSUE THREAD

**Issue by rousik** [lokalise/lokalise-cli-2-go#27]
The problem lies in the unmarshalling of the `TaskLanguage.task.languages.initial_tm_leverage`. Go expects this to be map[string]int64 and the API documentation does seem to indicate that this is what's expected (.e.g `{ '20%': 0, ...}`, but API does return empty lists instead of empty structure which breaks the parser:

```
json: cannot unmarshal array into Go struct field TaskLanguage.task.languages.initial_tm_leverage of type map[string]int64
```

**Comment by rousik** [comment]
Here's the snipped of the task response that is being parsed:
```
"languages": [
  {
    ...
    "status": "created",
    "progress": 0,
    "initial_tm_leverage": [],
    ...
```

**Comment by beinarovic** [comment]
Hey @rousik ,

Sorry for the late response... We got this fixed a while ago, it should work fine now.
