### ISSUE TITLE
download files with names match wildcards or regex

### ISSUE THREAD

**Issue by shiqi** [lokalise/lokalise-cli-2-go#28]
is there a way to specify a file name pattern with the file download command to only download files in the project that match a given pattern? e.g. `release-branch:*.json`
I found the `filter_filenames` but that doesn't seems to be the one from what I read about the description on that. if it in fact is designed for this, can I get an example on what I should assign to that paramater? Thanks

**Comment by beinarovic** [comment]
Hi, and sorry for the late response.

Currently our API does not have such matching filters. `filter_filenames` accepts array of filenames (exact match).

So the workaround would be listing filenames and using `filter_filenames`...
