### ISSUE TITLE
Docker image with version v2.5.1+

### ISSUE THREAD

**Issue by IASamoylov** [lokalise/lokalise-cli-2-go#34]
Hello, our team received an email about the new requried parameter `queue`, which will be enabled from July 1. We use docker image [lokalise/lokalise-cli-2](https://hub.docker.com/r/lokalise/lokalise-cli-2) and we are going to use it with flag `--poll`. DockerHub contains only version 2.3.0. Are you going to upload a new version?

**Comment by beinarovic** [comment]
Hello, the release is currently missing in DockerHub
It will be added soon. Sorry for the inconvenience.

**Comment by beinarovic** [comment]
@IASamoylov Thanks for rising this issue. We have added v2.5.1 to DockerHub.

**Comment by balloob** [comment]
FYI the new tag is `2.5.1`, older versions included the `v`, ie `v2.3.0`
