### ISSUE TITLE
Adopt SemVer

### ISSUE THREAD

**Issue by balloob** [lokalise/lokalise-cli-2-go#35]
It would be great if this CLI would adopt [Semantic Versioning](https://semver.org/) for its versioning. That way it would make it easier for Home Assistant to stay up to date. 

With Semantic Versioning, if you make a breaking API change (ie change a command line flag), you would bump a major version. That way consumers of your CLI that are upgrading know they need to look at the release notes.

Recent changes that were breaking:
 - 2.5.1 changes changed(/merged?) two parameter names
 - 2.5.0 changes default value of `convert-placeholders`

**Comment by nickustinov** [comment]
Thanks for the advice, however we decided to keep it at major version 2, as it's CLIv2, which works over APIv2 and the binary is called lokalise2. It would be irrational to rename it all at this point. We will switch to semantic versioning and different naming with a more global update.

**Comment by balloob** [comment]
Would it be possible to adopt an adapted version ? So make breaking changes when you go to 2.6, 2.7, but not when you go from 2.6.0 to 2.6.1 ? That way you can keep your `2` in the version number?

**Comment by beinarovic** [comment]
2.5.1 was a first day patch, the ‘—pool’ flag was introduced in 2.5.0 the same day. Otherwise we would bump a minor version.
