### ISSUE TITLE
Incorrect upload file on version v2.5.1 via docker image

### ISSUE THREAD

**Issue by IASamoylov** [lokalise/lokalise-cli-2-go#36]
After upgrading to version 2.5.1, template strings do not load correctly. 

Exmaple:

```json
{
    "bug": {
        "test_key": "Possible bug in {bugDescription}"
    }
}
```

Version 2.3.0:

![image](https://user-images.githubusercontent.com/19590161/84010038-c38c1d80-a97c-11ea-918a-df2845b15feb.png)

Version 2.5.1:

![image](https://user-images.githubusercontent.com/19590161/84010313-2a113b80-a97d-11ea-8598-53add6f4591e.png)

**Comment by beinarovic** [comment]
Hello.

We had an inconsistency in the cli flags. Cli has `--convert-placeholders=false` by default, but the. api's default was `true`.

In 2.5.0 we have changed the default to `--convert-placeholders=true`.

https://github.com/lokalise/lokalise-cli-2-go/releases/tag/v2.5.0

**Comment by IASamoylov** [comment]
I get the same result when `--convert-placeholder` is true and false. 

```bash
docker run --net=host --rm -v $($volume):/opt/src/en.json lokalise/lokalise-cli-2:2.5.1 lokalise2 --token $($token) --project-id $($projectId) file upload --replace-modified --file /opt/src/en.json --lang-iso en --convert-placeholders true --poll
```

![image](https://user-images.githubusercontent.com/19590161/84013500-ab6acd00-a981-11ea-9771-bbccd6ead6a2.png)

**Comment by beinarovic** [comment]
@IASamoylov The correct flag would be `--convert-placeholders=false` in your case.

**Comment by beinarovic** [comment]
The default was `false` before... And bool flags should be passed with `=` separator.

**Comment by IASamoylov** [comment]
@beinarovic thank you, this is working

**Comment by beinarovic** [comment]
No problem, have a nice day!
