### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by timstott** [lokalise/lokalise-cli-2-go#38]
:wave: Hi,

Could we please add a license to the repository to indicate what are the usage/distribution intents.

This resource may help in choosing a suitable license https://choosealicense.com/

Thank you for your amazing work :tada:

**Comment by beinarovic** [comment]
@timstott Hey! 

We are planning to add a license in the nearest future, thanks for your concerns. 🙂

**Comment by timstott** [comment]
Thanks @beinarovic, would you perhaps like to keep the issue open until it is resolved to help others track against it? :bow:

**Comment by beinarovic** [comment]
Hi @timstott ,

We have added the BSD-3-Clause license - https://github.com/lokalise/lokalise-cli-2-go/blob/master/LICENSE
