### ISSUE TITLE
i18next plural and placeholder format?

### ISSUE THREAD

**Issue by pepf** [lokalise/lokalise-cli-2-go#44]
We're using the i18next format in our app and use the cli to sync locales with Lokalise.
I figured out plural-format actually takes `i18next` as a value, so I'd be happy to make a pr for this to update the docs/cli.
Is there already a similar hidden option for the placeholder-format? Right now some of our exported .json files contain the curly brace syntax (the intended one) while others contain a more strange format, which obviously breaks our integrations 😅 . Thanks!

```sh
▶ lokalise2 --version           
lokalise2 version 2.6.0

## command we run to download locales
lokalise2 file download \
--project-id $PROJECT_ID \
--token $LOKALISE_TOKEN \
--format json \
--directory-prefix ""  \
--bundle-structure "" \
--original-filenames false \
--export-sort first_added \
--indentation 2sp \
--export-empty-as skip \
--json-unescaped-slashes  \
--plural-format i18next \  #<--- so this actually works
--unzip-to ./;
```

**Comment by beinarovic** [comment]
@pepf Hey!

About the docs - we'd be happy to accept your pr.
But we can't understand the issue with the strange format, can you please clarify?

**Comment by pepf** [comment]
ok will add those!
So the issue we had is as follows, in our project we expect interpolated (i18next format) variables in our translations like so:
```
{
  "some_key": "I have {{count}} apples"
}
```
But when leaving out the placeholder_format we get a different format in our .json files sometimes, mixed with the format we expect.
```
{
  "some_key": "I have {{count}} apples"
  "some_key2": "Message sent to %1$s.",

}
```

This is the main reason I opened the issue. Adding the placeholder format argument seems to "normalize" all of the placeholders to the right format 😄

**Comment by beinarovic** [comment]
This is expected behaviour when using universal placeholders in the project. That’s why you have to use the placeholder format. :)
