### ISSUE TITLE
Upload/download files should allow to specify branch

### ISSUE THREAD

**Issue by emartynov** [lokalise/lokalise-cli-2-go#46]
Hi people,

I'm working on the automation and our workflow is next:
1. Developer starts feature branch
2. Developer creates branch in lokalise
3. Developer updates translations files in the project
4. Developer uploads files to lokalise
5. Localization is provided
6. Developer pulls localization from lokalise
7. Developer merges pull request on GitHub and merges branch to main in lokalise

Unfortunately not all actions with lokalise are possible over CLI or API.

**Comment by beinarovic** [comment]
Hi @emartynov , have you reached out to our Tech support with this request? Sorry for the late response.

**Comment by emartynov** [comment]
Hey, yup! Can you close it?

**Comment by exodusanto** [comment]
If anyone needs [this](https://github.com/lokalise/lokalise-cli-2-go/issues/76#issuecomment-893226421) is the answer to use upload/download command with branches
