### ISSUE TITLE
replace-breaks option not working

### ISSUE THREAD

**Issue by podcast-studio-development** [lokalise/lokalise-cli-2-go#6]
The outputs of these two commands:

lokalise2 file download --token ${token} --project-id ${projectID} --format xliff --replace-breaks true

lokalise2 file download --token ${token} --project-id ${projectID} --format xliff --replace-breaks false

...return identical outputs even when there are keys that have line breaks in them. They always appear as \n in the xliff file despite the value of `replace-breaks`

**Comment by nickustinov** [comment]
It should be --replace-breaks=false (negative flags should be passed with = sign)
