### ISSUE TITLE
Allow to specify a configuration file with a --config flag

### ISSUE THREAD

**Issue by frabonomi** [lokalise/lokalise-cli-2-go#7]
With the old version of the CLI tool I was able to specify a configuration file like:

```bash
lokalise --config 'lokalise.cfg' …
```

With version 2 it looks like it's not possible anymore or am I missing something? Is it mandatory to have the file named `config.yml`?

**Comment by yarlson** [comment]
A version v2.2.0 with support for `--config` option has been released.
You can download it at https://github.com/lokalise/lokalise-cli-2-go/releases/tag/v2.2.0
