### ISSUE TITLE
Cannot specify branch when downloading files

### ISSUE THREAD

**Issue by dteoh** [lokalise/lokalise-cli-2-go#76]
How can I specify the branch when using `file download` command? I tried using `--branch`, `--branch-id` and `--branch-name` but it doesn't seem to be supported.

**Comment by andrewLab-lokalise** [comment]
Hey @dteoh,
To work with a branch, specify the branch name as part of `project-id` parameter, separated by semicolon , i.e. `3002780358964f9bab5a92.87762498:branch`
Refer to https://github.com/lokalise/lokalise-cli-2-go#branches

**Comment by dteoh** [comment]
Woops, thanks, should have checked the README 😅
