### ISSUE TITLE
How to download files with Android project structure?

### ISSUE THREAD

**Issue by chokokatana** [lokalise/lokalise-cli-2-go#8]
I've tried migrating lokalise script but don't know how to make it work like version 1. Using a command like this:
```
./extra/lokalise2  -t token --project-id id \
	file download strings.xml
	--format xml
	--unzip-to app/src/main/res
	--export-sort a_z
	--replace-breaks 1
	--indentation 4sp
```
…will generate files like:
```
app/src/main/res/en/strings.xml
app/src/main/res/es/strings.xml
```
However, this doesn't match the previously exported structure which is:
```
app/src/main/res/values/strings.xml
app/src/main/res/values-es/strings.xml
```
How can the old structure be preserved without custom post processing?

Also #7, due to policy.

**Comment by Test00103451010** [comment]
Could you try to use the following command

lokalise2 --token  --project-id 
file download 
--format xml 
--all-platforms 
--original-filenames FALSE 
--unzip-to "app/src/main/res\values-%LANG_ISO%/strings.xml"
--export-sort a_z
--replace-breaks 1
--indentation 4sp


Please check the article below for your reference:
https://docs.lokalise.com/en/articles/2281317-filenames

**Comment by stumi01** [comment]
we are using it like this in our scripts and its working.
`./lokalise2 file download --token "${LOKALISE_TOKEN}" --project-id "${LOCALISE_PROJECT}" --format xml --include-description False --original-filenames True --directory-prefix "" --export-sort "first_added" --export-empty-as "skip"`

Note we are uploading like this:
    `./lokalise2 file upload --token ${LOKALISE_TOKEN} --project-id ${LOCALISE_PROJECT} --lang-iso en --include-path true --file app/src/main/res/values/strings.xml,app/src/main/res-features/profile/values/strings.xml`

**Comment by chokokatana** [comment]
The solution by @Test00103451010 did not work, the replacement string was not updated, and even if it was, it would still create a `values-en` directory instead of `values`. But thanks to @stumi01 I got the idea of filtering single languages, so I can iterate over the list of languages and download each separately to a specific path.

Thanks.
