### ISSUE TITLE
New file created when uploading iOS strings file

### ISSUE THREAD

**Issue by stherold** [lokalise/lokalise-cli-2-go#82]
I use the following command to upload our iOS string files to lokalize:
```
lokalise2 \
        --token "$token" \
        --project-id "$project_id" \
        file upload \
        --cleanup-mode=true \
        --distinguish-by-file=true \
        --file "./resources/en-BZ.lproj/Strings.strings" \
        --include-path=true \
        --lang-iso "en_BZ" \
        --skip-detect-lang-iso=true \
        --replace-modified=true
```

Since Xcode sets it up this way we have the files in language folders with a language ID `en-BZ`. But on lokalise the ISO lang ID is `en_BZ` which we address by specifying the parameter `--lang-iso "en_BZ" \`. 

Since today the upload generates a **new** file whith the exact file name instead of merging the upload in the "wild-card file" `./resources/%LANG_ISO%.lproj/Strings.strings` which is already setup since years. 

When I do a file list with the command line tool I get both files but actually I only want the one with %LANG_ISO%:
```json
    {
      "filename": "./resources/%LANG_ISO%.lproj/Strings.strings",
      "key_count": 21
    },
    {
      "filename": "./resources/en-BZ.lproj/Strings.strings",
      "key_count": 21
    },
```

I have no clue how to fix this. It looks like lokalise used the exact file name and does not recognize that there is already this "wild-card file" existing...

Help

**Comment by andrewLab-lokalise** [comment]
Hey, @stherold, sorry for a late response. Does the problem still persist or it was resolved through our support?

**Comment by stherold** [comment]
Hey there 👋

Since this is a while ago, Idk how it was fixed but it works right now 😅

Let's close the issue :)
