### ISSUE TITLE
API file upload is replacing {{ with [%1$s: 

### ISSUE THREAD

**Issue by ATimshin** [lokalise/lokalise-cli-2-go#84]
Hello,

We're using Lokalize API to import keys and then export them after translation
Recently we've found that the following import command is importing improperly key values that are in {{ value }} brackets - they appear as [%1$s:value] in Web UI. Here's the command we use:
lokalise2 -t $(LokaliseToken) --project-id $(ProjectID) file upload --file $file.FullName --lang-iso en;

Even though Web UI shows these keys properly, these keys are breaking up after export via the same API:
![image](https://user-images.githubusercontent.com/93260700/139059055-27719503-495a-4c0f-ad31-98c4419bd513.png)
lokalise2 -t $(UDTLokaliseToken) --project-id $(ProjectID) file download --format json --original-filenames=false --export-sort=a_z 

So we send keys in {{}} and receive them in [%1$s:] brackets instead, please advise

**Comment by JayAhn2** [comment]
@ATimshin have you manage to fix this?
